### ISSUE TITLE
DDNet's Skin DB

### ISSUE THREAD

**Issue by Ekidoxx** [TeeworldsDB/skins#1]
Since DDNet's Skin Database is currently under cleanup, it would be great if all of the skins that were in it would be added to your DB, in case if that wasn't done already.

<br />
<br />

There you have skins in different directories for unsorted, sorted by author or sorted by skinpack.
Additionally there's big-ass screenshot of whole https://ddnet.tw/skins/ page with all the data aswell.

[DDNet Skin DB.zip](https://github.com/TeeworldsDB/skins/files/5248089/DDNet.Skin.DB.zip) backup from 17.09.2020

**Comment by ChillerDragon** [comment]
Added the skins without credits. One day I hope I feel extra motivated to research and add some authors and add tags and notes etc.
